#!/bin/sh

# Add this file to the SSH motd directory so the TapAPI logo shows up
# When SSH-ing into the server

echo " _______                  _____ _____"
echo "|__   __|           /\   |  __ \_   _|"
echo "   | | __ _ _ __   /  \  | |__) || |"
echo "   | |/ _` | '_ \ / /\ \ |  ___/ | |"
echo "   | | (_| | |_) / ____ \| |    _| |_"
echo "   |_|\__,_| .__/_/    \_\_|   |_____|"
echo "           | |"
echo "           |_|"
